[build]
    publish = "public"
    command = "echo No build command"
    node_bundler = "esbuild"

[dev]
    publish = "public"
    node_bundler = "esbuild"

[[headers]]
  for = "/.well-known/matrix/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "*"
    content-type = "application/json"
